routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Models\Note;
use App\Models\User;

Route::get('/', function () {
     return redirect('/notes');
})->middleware('auth');

Auth::routes();

Route::group(['middleware' => ['auth']], function (){
        Route::resource('notes', \App\Http\Controllers\NoteController::class);
        Route::get('link', [\App\Http\Controllers\NoteController::class, 'getLink'])->name('get-link');

        Route::get('/statistics', function () {
            $users = User::all();
            $data = [];
            foreach($users as $user){
                $on_date = Note::where('user_id', $user->id)->where('type', 'on date')->count();
                $urgent = Note::where('user_id', $user->id)->where('type', 'urgent')->count();
                $normal = Note::where('user_id', $user->id)->where('type', 'normal')->count();
                array_push($data, [
                    'name' => $user->name,
                    'urgent' => $urgent,
                    'normal' => $normal,
                    'on date' => $on_date,
                ]);
            }
            return view('stat', ['data' => $data]);
        })->name('stat');
});

Route::get('shared/{id}', [\App\Http\Controllers\NoteController::class, 'viewThroughLink'])->name('view-through-link');

app/Models/Note.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Note extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'id',
        'title',
        'content',
        'type',
        'user_id',
        'image'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }


}

app/Http/Controllers/NoteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Note;
use App\Models\SharedLink;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
class NoteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user() == null)
            return  redirect('/login');
        $user_id = Auth::user()->id;
        $notes = Note::where('user_id', $user_id)->paginate(6);

        return  view('notes.index', ['data' => $notes]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('notes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(),[
            'title' => 'required|string',
            'content' => 'required|string',
            'type' => 'required|string|in:on date,urgent,normal',
        ]);
        if($validator->fails())
        {
            return redirect()->back()
                        ->withErrsors($validator)
                        ->withInput();
        }
        $data = $validator->validated();
        $data['user_id'] = Auth::user()->id;
        if ($request->hasFile('image')) {
            if ($request->file('image')->isValid()) {
                $validated = $request->validate([
                    'image' => 'mimes:jpeg,png|max:2014',
                ]);

                $name = time().'_'.$validated['image']->getClientOriginalName();
                $validated['image']->storeAs('/public',$name);
                $data['image'] = $name;
            }
        }

        $note = Note::create($data);
        return  redirect(route('notes.index'))->with('success', 'Creating Note Completed');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $note = Note::where('id', $id)->first()->toArray();

        return view('notes.show', ['note' => $note]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $note = Note::where('id', $id)->first()->toArray();
        return view('notes.edit', ['note' => $note]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $validator = Validator::make($request->all(),[
            'title' => 'string',
            'content' => 'string',
            'type' => 'string|in:on date,urgent,normal',
        ]);
        if($validator->fails())
        {
            return redirect()->back()
                        ->withErrsors($validator)
                        ->withInput();
        }
        $data = $validator->validated();
        if ($request->hasFile('image')) {
            if ($request->file('image')->isValid()) {
                $validated = $request->validate([
                    'image' => 'mimes:jpeg,png|max:2014',
                ]);
                $name = time().'_'.$validated['image']->getClientOriginalName();
                $validated['image']->storeAs('/public',$name);
                $data['image'] = $name;
            }
        }

        $note = Note::where('id', $id)->where('user_id', Auth::user()->id)->update($data);
        return  redirect(route('notes.index'))->with('success', 'Updating Note Completed');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Note::where('id', $id)->first()->delete();
        return redirect(route('notes.index'))->with('alert', 'Delete Note Completed');
    }

    public function getLink(Request $request)
    {
        $note_id = $request->all()['id'];
        $sl = SharedLink::create(['note_id' => $note_id]);
        $link = route('view-through-link', $sl->id);
        return response()->json(['success' => $link], 200);
    }
    public function viewThroughLink($id)
    {
        $note_id = SharedLink::where('id', $id)->first()->note_id;

        $note = Note::where('id', $note_id)->first()->toArray();

        return view('notes.show', ['note' => $note]);
    }
}

resources/views/notes/create.blade.php
@extends('layouts.app')


@section('content')
<div class="container">
    <div class="row justify-content-center" style="margin-bottom: 10px;">
        <div class="col-md-5 ">
            <a style="width: 100%;" href="{{ route('notes.index') }}" class="btn btn-secondary">Back</a>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header" style="text-align: center;font-weight:bold;">New Note</div>
                <div class="card-body">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                    <form action="{{ route('notes.store') }}" method="post" enctype='multipart/form-data'>
                        {{ @csrf_field() }}
                        <div class="col-18 mb-3">
                            <label for="title" class="col-sm-2 col-form-label">Title</label>
                            <div class="col-md-18">
                              <input type="text" class="form-control" id="title" name = "title" value="{{ old('title') }}">
                            </div>
                          </div>
                        <div class="col-18 mb-3">
                            <label for="content" class="col-sm-2 col-form-label">Content</label>
                            <div class="col-md-18">
                              <textarea type="text" class="form-control" id="content" name = "content">{{ old('content') }}</textarea>
                            </div>
                          </div>
                        <div class="type">
                            <label for="type" class="form-label">Type</label>
                            <input class="form-control" list="types" id="type" placeholder="Choose one type, please." name="type" value="{{ old('type') }}">
                            <datalist id="types">
                                <option value="urgent">
                                <option value="on date">
                                <option value="normal">
                            </datalist>
                        </div>
                        <div class="image-input">
                            <div class="col-18 mb-3" style="margin-top:15px;">
                                <label for="image11" class="form-label">Attach Image(optional)</label>
                                <input class="form-control" type="file" id="image11" name="image">
                            </div>
                        </div>
                        <div class="row justify-content-center" style="margin-top: 30px;">
                            <div class="col-4">
                                <button type="submit" class="btn btn-success" style="width: 100%;">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/notes/edit.blade.php
@extends('layouts.app')

{{-- {{ dd($note) }} --}}
@section('content')
<div class="container">
    <div class="row justify-content-center" style="margin-bottom: 10px;">
        <div class="col-md-5 ">
            <a style="width: 100%;" href="{{ route('notes.index') }}" class="btn btn-secondary">Back</a>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header" style="text-align: center;font-weight:bold;">Edit Note</div>
                <div class="card-body">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                    <form action="{{ route('notes.update', $note['id']) }}" method="post" enctype="multipart/form-data">
                        {{ @csrf_field() }}
                        <input type="hidden" name="_method" value="PUT">
                        <div class="col-18 mb-3">
                            <label for="title" class="col-sm-2 col-form-label">Title</label>
                            <div class="col-md-18">
                              <input type="text" class="form-control" id="title" name = "title" value="{{ $note['title'] }}">
                            </div>
                          </div>
                        <div class="col-18 mb-3">
                            <label for="content" class="col-sm-2 col-form-label">Content</label>
                            <div class="col-md-18">
                              <textarea type="text" class="form-control" id="content" name = "content">{{ $note['content'] }}</textarea>
                            </div>
                          </div>
                        <div class="type">
                            <label for="type" class="form-label">Type</label>
                            <input class="form-control" list="types" id="type" placeholder="Choose one type, please." name="type" value="{{ $note['type'] }}">
                            <datalist id="types">
                                <option value="urgent">
                                <option value="on date">
                                <option value="normal">
                            </datalist>
                        </div>
                        <div class="image-input">
                            <div class="col-18 mb-3" style="margin-top:15px;">
                                <label for="image" class="form-label">Attach Image(optional)</label>
                                <input class="form-control" type="file" id="image" name="image">
                              </div>
                        </div>
                        <div class="row justify-content-center" style="margin-top: 30px;">
                            <div class="col-4">
                                <button type="submit" class="btn btn-success" style="width: 100%;">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/notes/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    {{-- {{ dd($success) }} --}}
    @if (session()->has('success'))
        <div class="alert alert-success" style="text-align: center;">
                {{ session()->get('success', 'Success!'); }}
        </div>
    @endif
    @if (session()->has('alert'))
        <div class="alert alert-danger" style="text-align: center;">
                {{ session()->get('alert', 'Success!'); }}
        </div>
    @endif
    <div class="row justify-content-center" style="margin-bottom:30px;">
        <div class="col-md-3">
            <a style="width:100%;" href="{{ route('notes.create') }}" class="btn btn-success"> Create Note </a>
        </div>
        <div class="col-md-3">
            <a style="width:100%;" href="{{ route('stat') }}" class="btn btn-secondary" style="color:cornsilk;"> Go to Report </a>
        </div>
    </div>

    <div class="row ">

    @foreach ($data as  $note)
        <div class="col-md-6" style="margin-bottom:30px;">
            <div class="card" id = "{{ $note->id }}">
                <div class="card-header" style="text-align: center;">{{ strlen($note->title) ? $note->title:'no title'}}</div>

                <div class="card-body" style="display: flex; justify-content:center;" >


                            <a href="{{ route('notes.show', $note->id) }}" class="btn btn-light" style="margin-right:7px;background-color: #BBB;border:4px #BBB;"> Show Details</a>
                            <a href="{{ route('notes.edit', $note->id) }}" class="btn btn-primary"style="margin-right:7px;" > Make Edits </a>


                </div>
            </div>
        </div>

        @endforeach
    </div>
    <div class="d-flex justify-content-center">
        {!! $data->links() !!}
    </div>

</div>
@endsection

resources/views/notes/show.blade.php
@extends('layouts.app')


@section('content')
{{-- {{ dd($note['content']) }} --}}

<div class="container">
    @if (Auth::user() != null)
        <div class="row justify-content-center" style="margin-bottom: 10px;">
            <div class="col-md-5 ">
                <a style="width: 100%;" href="{{ route('notes.index') }}" class="btn btn-secondary">Back</a>
            </div>
        </div>
    @endif

    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header" style="text-align: center;font-weight:bold;">{{ strlen($note['title']) ? $note['title']:"No Title";  }}</div>
                <div class="card-body" style="padding-bottom: 6%;">
                    <div class="col-18 mb-3">
                        <label for="content" class="col-sm-2 col-form-label">Content</label>
                        <div class="col-md-18">
                            <textarea   rows="4"  class="form-control" id="content"  readonly>{{ trim($note['content']) }}</textarea>
                        </div>
                        </div>
                    <div class="type col-18 mb-3">
                        <label for="type" class="form-label">Type</label>
                        <input class="form-control" type="text" name="type" disabled value={{ $note['type'] }}>
                    </div>
                    <div class="image col-18 mb-3"  >
                        <label for="image" class="form-label">Attached Image</label>
                        <div class="col-18 justify-content-center" class="form-label">
                            {{-- {{ dd($note['image']) }} --}}
                            <img src="{{ url('/storage/'.$note['image'])  }}" class="img-thumbnail"  alt="no image attached!" width="250px" height="200px">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @if (Auth::user() != null)
    <div class="row justify-content-center" style="margin-top:20px;">

        <div class="col-md-3">
            <button style="width:100%;"  class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" style="color:cornsilk;" onmousedown="getLink({{ $note['id'] }})"> Get Link </button>
        </div>
        <div class="col-md-3">
            <form action="{{ route('notes.destroy',$note['id']) }}" method="post">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="DELETE">
                <button style="width:100%;"  class="btn btn-danger"> Delete Note </button>
            </form>

        </div>
    </div>
    @endif
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Public Link</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id = "foo">
          ...
        </div>
      </div>
    </div>
  </div>
@endsection
<script>
    function getLink(note_id){
        let _token = $('meta[name="csrf-token"]').attr('content');

        $.ajax({
            url: "{{route('get-link')}}",
            type: "get",
            data: {
                id: note_id,
                _token: _token
            },
            success: function(response) {
                console.log(response.success);
                let container = document.getElementById('foo');
                container.innerHTML = response.success;
            },
            error: function(error) {
                console.log(error);
            }
        });

    }
</script>